version: '3.5'

name: 'test-scenario-compare-files'

services:
  testcontainer:
    image: debian:latest
    container_name: test-compare-files-container
    environment:
    - ALIVE=true
    volumes:
    - ./files:/tmp/files