#https://avatars.githubusercontent.com/u/5375661?s=200&v=4
version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - dashnet
    volumes:
      - /tmp/node-red-data:/data

volumes:
  node-red-data:

networks:
  dashnet: