version: '3.9'

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - "/tmp/iobrokerdata:/opt/iobroker"
