services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../portainer_data:/data"
    restart: always
    networks:
      dashnet:
        ipv4_address: 10.0.0.3

networks:
  dashnet:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"

# volumes:
#   portainer_data: