version: '3.5'
networks:
    dashnet:
        driver: ${networkdriver}
        ipam:
            config:
            - subnet: ${subnet}
services:
    service-name:
        container_name: ${name}
        volumes:
        - ${volumepath}:/app
        - ${cronpath}:/etc/cron.d
        - ${logspath}:/var/log
        - ${scriptspath}:/usr/local/scripts
        - ${miscpath:-/dev/null}:${miscpathdest:-/dev/null}
        - ${dockersock:-/dev/zero}:${dockersock:-/dev/zero}
        
        # devices:

        build:
            context: ${context}
            dockerfile: ${dockerfile}
        working_dir: /app
        entrypoint: >
            bash -c "chmod +x /usr/local/scripts/* && /usr/local/scripts/cron_setup.sh && ${entrypoint}"
        environment:
        - ALIVE=true
        networks:
            dashnet:
                ipv4_address: ${ipv4_address}
        ports:
        - ${ports}
        healthcheck:
            test: ["CMD", "curl", "-f", "${restapiurl}/status"]
            interval: ${interval}
            timeout: ${timeout}
            retries: ${retries}
            start_period: ${startperiod}


