# base on debian
FROM ${image}
RUN apt update

# Cron
RUN apt -y install cron curl

# cron.d directory
COPY crontask /etc/cron.d/crontask
 
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontask

# Apply cron job
RUN crontab /etc/cron.d/crontask
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
