# base on debian
FROM debian:latest

RUN apt-get update

# Docker Compose
RUN apt-get -y install docker-compose docker.io

# Cron
RUN apt-get -y install cron curl

# Python for rest api
RUN apt install -y \
	python3 python3-pip

RUN pip3 install \
    flask pyyaml

# cron.d directory
COPY ./cron/crontask /etc/cron.d/crontask
 
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontask

# Apply cron job
RUN crontab /etc/cron.d/crontask
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log && 
